### ISSUE TITLE
Add docker setup documentation in contribution guide.

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-docs#10]
Ref: https://github.com/saeloun/miru-web/pull/720

**Comment by rajat-tomar** [comment]
@akhilgkrishnan can you please elaborate a little, where exactly do we want to put installation setup in contribution guide. Rest you can assign this task to me if possible. I would like to work on this.

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan can you please elaborate a little, where exactly do we want to put installation setup in contribution guide. Rest you can assign this task to me if possible. I would like to work on this.

You need to write a documentation for how we can setup the Miru application using docker. You can also refer macOS setup guide.

**Comment by rajat-tomar** [comment]
Hey @akhilgkrishnan just added Pull request with the docker setup guide. Please check PR #11

**Comment by rajat-tomar** [comment]
@supriya3105 can you please look into the PR. Seems like @akhilgkrishnan is not available

**Comment by akhilgkrishnan** [comment]
Docker setup was already added
