### ISSUE TITLE
Add a Miru app setup documentation for Ubuntu

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-docs#2]

**Comment by aaj013** [comment]
I'd like to work on this

**Comment by akhilgkrishnan** [comment]
@aaj013 Assigned the ticket to you. I saw you had raised a PR. Thanks for working on this
Please note: Do not create a PR without assigning the ticket.

**Comment by aaj013** [comment]
> @aaj013 Assigned the ticket to you. I saw you had raised a PR. Thanks for working on this Please note: Do not create a PR without assigning the ticket.

My bad. You can close it then, as it made a violation.
